# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [1]:
def share_bread(N, K):
    
    return K//N, K%N

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [2]:
def leap_year(year):
    if (year%4 == 0) and (year%100 != 0) or (year%400 == 0):
        return 'YOU SHALL PASS'
    return "YOU SHALL NOT PASS"

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [3]:
def amulet_area(a, b, c):
    p = (a + b + c)/2
    S = (p*(p-a)*(p-b)*(p-c))**0.5
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [1]:
import numpy as np

def cal_euclidean(a, b):    
    return np.sqrt(np.sum(np.square(a-b)))

def cal_manhattan(a, b):    
    return np.sqrt(np.sum(np.abs(a-b)))
    
def cal_cosine(a, b):    
    distance = 1- np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
    return distance

In [2]:
np.random.seed(123)
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

31.32091952673165
9.1104335791443
0.9684080598528484


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [10]:
my_array = np.random.rand(100)
my_array[np.argmax(my_array)], my_array[np.argmin(my_array)] = 1, 0
print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0.91977584 0.16609828 0.75446511 0.97852652 0.98778374 0.78787105
 0.4297222  0.12449379 0.24328085 0.12214056 0.88351529 0.55459527
 0.55261806 0.37980344 0.02944013 0.66767244 0.16090518 0.51856531
 0.55293146 0.69045392 0.27758594 0.42285834 0.56139361 0.3532924
 0.36291164 0.1588661  0.22092845 0.35713037 0.10407565 0.89186795
 0.43756625 0.75233314 0.46353502 0.24566366 0.42560804 0.92235389
 1.         0.60071558 0.64350212 0.86698615 0.919924   0.39961451
 0.27770817 0.71651939 0.64485004 0.49552885 0.82793461 0.87907025
 0.70739934 0.28293813 0.61589462 0.44475636 0.98911705 0.72317806
 0.85698024 0.46152394 0.11851899 0.22401331 0.7799942  0.7922671
 0.56930545 0.35134755 0.55746802 0.16572225 0.70907015 0.19056304
 0.30636887 0.34107057 0.         0.42229943 0.83009542 0.17377143
 0.38918554 0.79638168 0.53250609 0.43360206 0.46067294 0.85472214
 0.07498101 0.45147028 0.74432839 0.62461425 0.08702104 0.74189438
 0.52707336 0.5938379  0.56469462 0.89363593 0.25136883 

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [16]:
np.random.seed(122)

my_array = np.random.uniform(0,50, size=(5,6))
selected_column = np.max(my_array, axis=0)
n = np.argmax(selected_column)

print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(f'{my_array[:, n]}')

[29.1540302  42.3414359  42.04392049 41.67535334 34.85302641 45.47376101]
Shape:  (5, 6)
Array
[[ 7.84959189 35.11050212 13.07391332 22.5856454  20.40326324 30.57706056]
 [29.1540302  10.72544353  9.438655   35.1048987  23.54088349 24.25264344]
 [ 5.05771944 18.00930563  1.3945553  11.87132707 27.9445284  10.16089076]
 [28.41676649 42.3414359  42.04392049 21.90026619 34.85302641 45.47376101]
 [16.48480383  9.27843136 11.65136131 41.67535334  0.5290534  12.80153123]]
[array([30.57706056, 24.25264344, 10.16089076, 45.47376101, 12.80153123])] 
 [30.57706056 24.25264344 10.16089076 45.47376101 12.80153123]


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [20]:
def get_unique_rows(X):
#     X_unique = []
#     X_unique += [X[i,:] for i in range(X.shape[0]) if not(X[i,:] in X_unique)]
    return np.unique(X, axis=0)

In [21]:
np.random.seed(123)
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[4 5 4]
 [4 4 4]
 [4 5 5]
 [4 5 5]
 [4 5 4]
 [5 4 5]
 [5 4 4]
 [4 5 5]
 [5 4 5]
 [4 4 4]]


In [22]:
get_unique_rows(X)

array([[4, 4, 4],
       [4, 5, 4],
       [4, 5, 5],
       [5, 4, 4],
       [5, 4, 5]])